//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_UdlaanRegistrering
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Elev()
        {
            this.Udlån = new HashSet<Udlån>();
        }
    
        public int Elevnummer { get; set; }
        public string CPR { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public string Postnr { get; set; }
        public string Email { get; set; }
        public string Stamklasse { get; set; }
    
        public virtual Postnummer Postnummer { get; set; }
        public virtual Stamklasse Stamklasse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Udlån> Udlån { get; set; }
    }
}
