//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_UdlaanRegistrering
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistreringDBEntities2 : DbContext
    {
        public RegistreringDBEntities2()
            : base("name=RegistreringDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<Elev> Elev { get; set; }
        public virtual DbSet<Fabrikat> Fabrikat { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Mus> Mus { get; set; }
        public virtual DbSet<Postnummer> Postnummer { get; set; }
        public virtual DbSet<Stamklasse> Stamklasse { get; set; }
        public virtual DbSet<Udlån> Udlån { get; set; }
    }
}
