//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_UdlaanRegistrering
{
    using System;
    using System.Collections.Generic;
    
    public partial class Udlån
    {
        public int Id { get; set; }
        public int Elevnummer { get; set; }
        public string Mus { get; set; }
        public System.DateTime Udlånsdato { get; set; }
        public System.DateTime Udløbsdato { get; set; }
    
        public virtual Elev Elev { get; set; }
        public virtual Mus Mus1 { get; set; }
    }
}
